"""Shared Slack Block Kit helpers for workflow payload generators."""

from __future__ import annotations

import datetime
import re
from typing import Optional

# Slack user group mention for Server Foundation team
SF_GROUP_MENTION = "<!subteam^S04N59L7UPR|acm-server-foundation>"

JIRA_BROWSE_BASE = "https://redhat.atlassian.net/browse"


def today_iso() -> str:
    """Return today's date as ISO string (YYYY-MM-DD)."""
    return datetime.date.today().isoformat()


def escape_mrkdwn(text: str) -> str:
    """Escape Slack mrkdwn special characters."""
    if text is None:
        return ""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def linkify_issue_keys(text: str) -> str:
    """Replace ACM-12345 keys with clickable Jira links in Slack mrkdwn.

    Must be called AFTER escape_mrkdwn since we insert raw < > for Slack links.
    """
    def _replace(match: re.Match[str]) -> str:
        key = match.group(0)
        return f"<{JIRA_BROWSE_BASE}/{key}|{key}>"

    return re.sub(r"ACM-\d+", _replace, text)


def truncate(text: str, max_len: int, suffix: str = "\u2026") -> str:
    """Truncate text to max_len, appending suffix if truncated."""
    if len(text) <= max_len:
        return text
    return text[: max_len - len(suffix)] + suffix


def health_emoji(health_pct: int) -> str:
    """Return a heart emoji reflecting health percentage (green/yellow/red)."""
    if health_pct >= 60:
        return "\U0001f49a"  # green heart
    if health_pct >= 40:
        return "\U0001f49b"  # yellow heart
    return "\u2764\ufe0f"  # red heart


def header_block(title: str) -> dict:
    """Build a Slack header block with plain_text."""
    return {
        "type": "header",
        "text": {"type": "plain_text", "text": title},
    }


def divider_block() -> dict:
    """Build a Slack divider block."""
    return {"type": "divider"}


def section_mrkdwn(text: str) -> dict:
    """Build a Slack section block with mrkdwn text."""
    return {"type": "section", "text": {"type": "mrkdwn", "text": text}}


def agent_footer_block(date: Optional[str] = None) -> dict:
    """Build the standard agent context footer block."""
    day = date or today_iso()
    return {
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"Generated by server-foundation-agent \u00b7 {day}",
            }
        ],
    }
