apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server-foundation
resources:
  - namespace.yaml
  - rbac.yaml
  - agenttemplate.yaml
  - agent.yaml
  - crontasks/weekly-pr-report.yaml
  - crontasks/weekly-bot-pr-hygiene.yaml
  - crontasks/daily-bug-triage.yaml
  - crontasks/daily-scrum-prep.yaml
